import { execFileSync } from 'node:child_process';
import { appendFileSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

export const ROOT = resolve(HERE, '../../../');
export const TEST_DIR = process.env.SPROUTGIT_E2E_TEST_DIR ?? join(ROOT, 'tmp', 'test');
export const REPOS_DIR = join(TEST_DIR, 'repos');
export const CANARIES_DIR = join(TEST_DIR, 'canaries');
export const CONFIG_DB_PATH = process.env.SPROUTGIT_CONFIG_DB_PATH;

const BASE_GIT_ENV = {
  GIT_AUTHOR_NAME: 'SproutGit Test',
  GIT_AUTHOR_EMAIL: 'test@sproutgit.test',
  GIT_COMMITTER_NAME: 'SproutGit Test',
  GIT_COMMITTER_EMAIL: 'test@sproutgit.test',
  GIT_TERMINAL_PROMPT: '0',
};

function commitDate(sequence: number) {
  return new Date(Date.UTC(2024, 0, 1, 12, sequence, 0)).toISOString();
}

function gitEnv(sequence: number) {
  const date = commitDate(sequence);
  return {
    ...BASE_GIT_ENV,
    GIT_AUTHOR_DATE: date,
    GIT_COMMITTER_DATE: date,
  };
}

export function runGit(cwd: string, args: string[], extraEnv: Record<string, string> = {}) {
  return execFileSync('git', args, {
    cwd,
    env: { ...process.env, ...BASE_GIT_ENV, ...extraEnv },
    stdio: 'pipe',
  })
    .toString()
    .trim();
}

export function cleanupTestDirs() {
  rmSync(TEST_DIR, { recursive: true, force: true });
}

export function setupTestDirs() {
  mkdirSync(REPOS_DIR, { recursive: true });
  mkdirSync(CANARIES_DIR, { recursive: true });
}

export function resetTestDirs() {
  cleanupTestDirs();
  setupTestDirs();
}

export function resetConfigDb() {
  if (CONFIG_DB_PATH) {
    rmSync(CONFIG_DB_PATH, { force: true });
  }
}

export function commitAll(repoPath: string, message: string, sequence: number) {
  runGit(repoPath, ['add', '--all']);
  runGit(repoPath, ['commit', '-m', message], gitEnv(sequence));
}

export function checkout(repoPath: string, ref: string, create = false) {
  runGit(repoPath, create ? ['checkout', '-b', ref] : ['checkout', ref]);
}

export function mergeNoFastForward(repoPath: string, ref: string, message: string, sequence: number) {
  runGit(repoPath, ['merge', '--no-ff', ref, '-m', message], gitEnv(sequence));
}

export function createAnnotatedTag(repoPath: string, tag: string, message: string, sequence: number) {
  runGit(repoPath, ['tag', '-a', tag, '-m', message], gitEnv(sequence));
}

export function writeRepoFile(repoPath: string, relativePath: string, content: string) {
  const absolutePath = join(repoPath, relativePath);
  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, content);
  return absolutePath;
}

export function appendRepoFile(repoPath: string, relativePath: string, line: string) {
  appendFileSync(join(repoPath, relativePath), `${line}\n`);
}

interface CreateTestRepoOptions {
  extraCommits?: number;
  branches?: string[];
  files?: Record<string, string>;
}

export function createTestRepo(name: string, opts: CreateTestRepoOptions = {}) {
  const {
    extraCommits = 0,
    branches = [],
    files = {},
  } = opts;

  const repoPath = join(REPOS_DIR, name);
  mkdirSync(repoPath, { recursive: true });

  runGit(repoPath, ['init', '-b', 'main']);
  runGit(repoPath, ['config', 'user.email', 'test@sproutgit.test']);
  runGit(repoPath, ['config', 'user.name', 'SproutGit Test']);

  writeRepoFile(repoPath, 'README.md', `# ${name}\n\nGenerated by SproutGit E2E tests.\n`);
  for (const [relativePath, content] of Object.entries(files)) {
    writeRepoFile(repoPath, relativePath, content);
  }
  commitAll(repoPath, 'Initial commit', 0);

  for (let index = 1; index <= extraCommits; index += 1) {
    writeRepoFile(repoPath, `docs/note-${index}.md`, `note ${index}\n`);
    commitAll(repoPath, `Add note ${index}`, index);
  }

  for (const branch of branches) {
    runGit(repoPath, ['branch', branch]);
  }

  return repoPath;
}

export function cloneCanaryRepo(targetPath: string, remoteUrl: string, ref: string | null = null) {
  rmSync(targetPath, { recursive: true, force: true });
  runGit(TEST_DIR, ['clone', '--depth', '1', remoteUrl, targetPath]);
  if (ref) {
    runGit(targetPath, ['fetch', '--depth', '1', 'origin', ref]);
    runGit(targetPath, ['checkout', ref]);
  }
  return targetPath;
}
