import { test, expect } from '../fixtures';
import { createTestRepo, resetConfigDb, resetTestDirs, writeRepoFile } from '../helpers/fixtures';
import { createWorktreeViaUi, DEFAULT_UI_TIMEOUT, importRepoViaUi, openChangesTab, openHistoryTab, reloadToHome } from '../helpers/ui';

test.describe('Commit workflow', () => {
  test.beforeEach(async ({ tauriPage }) => {
    resetTestDirs();
    resetConfigDb();
    await reloadToHome(tauriPage);
  });

  test('stages and commits changes from a managed worktree', async ({ tauriPage }) => {
    const repoPath = createTestRepo('commit-test', { extraCommits: 1 });

    await importRepoViaUi(tauriPage, repoPath);
    await createWorktreeViaUi(tauriPage, 'feature/e2e-commit');

    const worktreeItem = tauriPage.locator('[data-testid="worktree-item"][data-branch="feature/e2e-commit"]');

    const worktreePath = await worktreeItem.getAttribute('data-path') ?? (() => { throw new Error('worktree-item missing data-path'); })();
    const filename = `e2e-${Date.now()}.txt`;
    writeRepoFile(worktreePath, filename, 'Generated by Playwright E2E\n');

    await openChangesTab(tauriPage);
    await tauriPage.locator(`[data-testid="unstaged-file"][data-filepath="${filename}"]`).waitFor(DEFAULT_UI_TIMEOUT);

    await tauriPage.getByTestId('btn-stage-all').click();
    const stageDeadline = Date.now() + DEFAULT_UI_TIMEOUT;
    while (Date.now() < stageDeadline) {
      const stillUnstaged = await tauriPage.isVisible(
        `[data-testid="unstaged-file"][data-filepath="${filename}"]`,
      );
      const nowStaged = await tauriPage.isVisible(
        `[data-testid="staged-file"][data-filepath="${filename}"]`,
      );

      if (!stillUnstaged || nowStaged) {
        break;
      }

      await new Promise(resolve => setTimeout(resolve, 120));
    }

    const commitMessage = `e2e: add ${filename}`;
    await tauriPage.evaluate(`(() => {
      const field = document.querySelector('[data-testid="commit-message"]');
      if (!(field instanceof HTMLTextAreaElement)) {
        throw new Error('commit-message is not a textarea');
      }
      field.value = ${JSON.stringify(commitMessage)};
      field.dispatchEvent(new Event('input', { bubbles: true }));
    })()`);
    const commitButton = tauriPage.getByTestId('btn-commit');
    const commitReadyDeadline = Date.now() + DEFAULT_UI_TIMEOUT;
    while (Date.now() < commitReadyDeadline) {
      if (!(await commitButton.getAttribute('disabled'))) {
        break;
      }
      await new Promise(resolve => setTimeout(resolve, 120));
    }
    await commitButton.click();

    const commitResultDeadline = Date.now() + DEFAULT_UI_TIMEOUT;
    let commitFailedMessage = '';
    while (Date.now() < commitResultDeadline) {
      const successToasts = await tauriPage.allTextContents(
        '[data-testid="toast-item"][data-toast-type="success"] [data-testid="toast-message"]',
      );
      if (successToasts.some((message) => message.includes(commitMessage))) {
        break;
      }

      const errorToasts = await tauriPage.allTextContents(
        '[data-testid="toast-item"][data-toast-type="error"] [data-testid="toast-message"]',
      );
      commitFailedMessage = errorToasts.find(Boolean) ?? '';
      if (commitFailedMessage) {
        throw new Error(`Commit failed: ${commitFailedMessage}`);
      }

      await new Promise(resolve => setTimeout(resolve, 120));
    }

    await openHistoryTab(tauriPage);
    await tauriPage.waitForFunction(
      `Array.from(document.querySelectorAll('[data-testid="commit-row"]')).some((row) => row.textContent?.includes(${JSON.stringify(commitMessage)}))`,
      DEFAULT_UI_TIMEOUT,
    );
  });
});